language: python
dist: trusty
sudo: required
services:
  - docker
python: 3.6
addons:
  apt:
    packages:
      - xvfb
      - chromium-browser
install:
  - git clone https://github.com/skyportal/skyportal.git skyportal
  - (cd skyportal && git show | cat)
  - make -C skyportal baselayer/README.md
  - pip install -r skyportal/baselayer/requirements.txt
  - pip install -r skyportal/requirements.txt
  - wget http://chromedriver.storage.googleapis.com/2.29/chromedriver_linux64.zip
  - sudo unzip chromedriver_linux64.zip chromedriver -d /usr/local/bin
  - rm chromedriver_linux64.zip
  - which chromium-browser
  - chromium-browser --version
script: ./docker_build.sh
after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push skyportal/web
